export const AIRPORTS = [
  {
    id: "6523",
    ident: "00A",
    type: "heliport",
    name: "Total RF Heliport",
    latitude_deg: "40.070985",
    longitude_deg: "-74.933689",
    elevation_ft: "11",
    continent: "NA",
    iso_country: "US",
    iso_region: "US-PA",
    municipality: "Bensalem",
    scheduled_service: "no",
    gps_code: "K00A",
    iata_code: "",
    local_code: "00A",
    home_link:
      "https://www.penndot.pa.gov/TravelInPA/airports-pa/Pages/Total-RF-Heliport.aspx",
    wikipedia_link: "",
    keywords: "",
  },
  {
    id: "323361",
    ident: "00AA",
    type: "small_airport",
    name: "Aero B Ranch Airport",
    latitude_deg: "38.704022",
    longitude_deg: "-101.473911",
    elevation_ft: "3435",
    continent: "NA",
    iso_country: "US",
    iso_region: "US-KS",
    municipality: "Leoti",
    scheduled_service: "no",
    gps_code: "00AA",
    iata_code: "",
    local_code: "00AA",
    home_link: "",
    wikipedia_link: "",
    keywords: "",
  },
  {
    id: "6524",
    ident: "00AK",
    type: "small_airport",
    name: "Lowell Field",
    latitude_deg: "59.947733",
    longitude_deg: "-151.692524",
    elevation_ft: "450",
    continent: "NA",
    iso_country: "US",
    iso_region: "US-AK",
    municipality: "Anchor Point",
    scheduled_service: "no",
    gps_code: "00AK",
    iata_code: "",
    local_code: "00AK",
    home_link: "",
    wikipedia_link: "",
    keywords: "",
  },
  {
    id: "6525",
    ident: "00AL",
    type: "small_airport",
    name: "Epps Airpark",
    latitude_deg: "34.86479949951172",
    longitude_deg: "-86.77030181884766",
    elevation_ft: "820",
    continent: "NA",
    iso_country: "US",
    iso_region: "US-AL",
    municipality: "Harvest",
    scheduled_service: "no",
    gps_code: "00AL",
    iata_code: "",
    local_code: "00AL",
    home_link: "",
    wikipedia_link: "",
    keywords: "",
  },
];
