export const AIRPORTS = [
  {
    id: "6523",
    ident: "00A",
    type: "heliport",
    name: "Total RF Heliport",
    latitude_deg: "40.070985",
    longitude_deg: "-74.933689",
    elevation_ft: "11",
    continent: "NA",
    iso_country: "US",
    iso_region: "US-PA",
    municipality: "Bensalem",
    scheduled_service: "no",
    gps_code: "K00A",
    iata_code: "",
    local_code: "00A",
    home_link:
      "https://www.penndot.pa.gov/TravelInPA/airports-pa/Pages/Total-RF-Heliport.aspx",
    wikipedia_link: "",
    keywords: "",
  },
  {
    id: "323361",
    ident: "00AA",
    type: "small_airport",
    name: "Aero B Ranch Airport",
    latitude_deg: "38.704022",
    longitude_deg: "-101.473911",
    elevation_ft: "3435",
    continent: "NA",
    iso_country: "US",
    iso_region: "US-KS",
    municipality: "Leoti",
    scheduled_service: "no",
    gps_code: "00AA",
    iata_code: "",
    local_code: "00AA",
    home_link: "",
    wikipedia_link: "",
    keywords: "",
  },
  {
    id: "6524",
    ident: "00AK",
    type: "small_airport",
    name: "Lowell Field",
    latitude_deg: "59.947733",
    longitude_deg: "-151.692524",
    elevation_ft: "450",
    continent: "NA",
    iso_country: "US",
    iso_region: "US-AK",
    municipality: "Anchor Point",
    scheduled_service: "no",
    gps_code: "00AK",
    iata_code: "",
    local_code: "00AK",
    home_link: "",
    wikipedia_link: "",
    keywords: "",
  },
  {
    id: "6525",
    ident: "00AL",
    type: "small_airport",
    name: "Epps Airpark",
    latitude_deg: "34.86479949951172",
    longitude_deg: "-86.77030181884766",
    elevation_ft: "820",
    continent: "NA",
    iso_country: "US",
    iso_region: "US-AL",
    municipality: "Harvest",
    scheduled_service: "no",
    gps_code: "00AL",
    iata_code: "",
    local_code: "00AL",
    home_link: "",
    wikipedia_link: "",
    keywords: "",
  },
  {
    id: "506791",
    ident: "00AN",
    type: "small_airport",
    name: "Katmai Lodge Airport",
    latitude_deg: "59.093287",
    longitude_deg: "-156.456699",
    elevation_ft: "80",
    continent: "NA",
    iso_country: "US",
    iso_region: "US-AK",
    municipality: "King Salmon",
    scheduled_service: "no",
    gps_code: "00AN",
    iata_code: "",
    local_code: "00AN",
    home_link: "",
    wikipedia_link: "",
    keywords: "",
  },
  {
    id: "6526",
    ident: "00AR",
    type: "closed",
    name: "Newport Hospital & Clinic Heliport",
    latitude_deg: "35.6087",
    longitude_deg: "-91.254898",
    elevation_ft: "237",
    continent: "NA",
    iso_country: "US",
    iso_region: "US-AR",
    municipality: "Newport",
    scheduled_service: "no",
    gps_code: "",
    iata_code: "",
    local_code: "",
    home_link: "",
    wikipedia_link: "",
    keywords: "00AR",
  },
  {
    id: "322127",
    ident: "00AS",
    type: "small_airport",
    name: "Fulton Airport",
    latitude_deg: "34.9428028",
    longitude_deg: "-97.8180194",
    elevation_ft: "1100",
    continent: "NA",
    iso_country: "US",
    iso_region: "US-OK",
    municipality: "Alex",
    scheduled_service: "no",
    gps_code: "00AS",
    iata_code: "",
    local_code: "00AS",
    home_link: "",
    wikipedia_link: "",
    keywords: "",
  },
  {
    id: "6527",
    ident: "00AZ",
    type: "small_airport",
    name: "Cordes Airport",
    latitude_deg: "34.305599212646484",
    longitude_deg: "-112.16500091552734",
    elevation_ft: "3810",
    continent: "NA",
    iso_country: "US",
    iso_region: "US-AZ",
    municipality: "Cordes",
    scheduled_service: "no",
    gps_code: "00AZ",
    iata_code: "",
    local_code: "00AZ",
    home_link: "",
    wikipedia_link: "",
    keywords: "",
  },
  {
    id: "6528",
    ident: "00CA",
    type: "small_airport",
    name: "Goldstone (GTS) Airport",
    latitude_deg: "35.35474",
    longitude_deg: "-116.885329",
    elevation_ft: "3038",
    continent: "NA",
    iso_country: "US",
    iso_region: "US-CA",
    municipality: "Barstow",
    scheduled_service: "no",
    gps_code: "00CA",
    iata_code: "",
    local_code: "00CA",
    home_link: "",
    wikipedia_link: "",
    keywords: "",
  },
  {
    id: "324424",
    ident: "00CL",
    type: "small_airport",
    name: "Williams Ag Airport",
    latitude_deg: "39.427188",
    longitude_deg: "-121.763427",
    elevation_ft: "87",
    continent: "NA",
    iso_country: "US",
    iso_region: "US-CA",
    municipality: "Biggs",
    scheduled_service: "no",
    gps_code: "00CL",
    iata_code: "",
    local_code: "00CL",
    home_link: "",
    wikipedia_link: "",
    keywords: "",
  },
  {
    id: "322658",
    ident: "00CN",
    type: "heliport",
    name: "Kitchen Creek Helibase Heliport",
    latitude_deg: "32.7273736",
    longitude_deg: "-116.4597417",
    elevation_ft: "3350",
    continent: "NA",
    iso_country: "US",
    iso_region: "US-CA",
    municipality: "Pine Valley",
    scheduled_service: "no",
    gps_code: "00CN",
    iata_code: "",
    local_code: "00CN",
    home_link: "",
    wikipedia_link: "",
    keywords: "",
  },
  {
    id: "6529",
    ident: "00CO",
    type: "closed",
    name: "Cass Field",
    latitude_deg: "40.622202",
    longitude_deg: "-104.344002",
    elevation_ft: "4830",
    continent: "NA",
    iso_country: "US",
    iso_region: "US-CO",
    municipality: "Briggsdale",
    scheduled_service: "no",
    gps_code: "",
    iata_code: "",
    local_code: "",
    home_link: "",
    wikipedia_link: "",
    keywords: "00CO",
  },
  {
    id: "6531",
    ident: "00FA",
    type: "small_airport",
    name: "Grass Patch Airport",
    latitude_deg: "28.64550018310547",
    longitude_deg: "-82.21900177001953",
    elevation_ft: "53",
    continent: "NA",
    iso_country: "US",
    iso_region: "US-FL",
    municipality: "Bushnell",
    scheduled_service: "no",
    gps_code: "00FA",
    iata_code: "",
    local_code: "00FA",
    home_link: "",
    wikipedia_link: "",
    keywords: "",
  },
  {
    id: "6694",
    ident: "02WN",
    type: "small_airport",
    name: "Fowler Field",
    latitude_deg: "48.74580001831055",
    longitude_deg: "-119.31900024414062",
    elevation_ft: "2150",
    continent: "NA",
    iso_country: "US",
    iso_region: "US-WA",
    municipality: "Tonasket",
    scheduled_service: "no",
    gps_code: "02WN",
    iata_code: "",
    local_code: "02WN",
    home_link: "",
    wikipedia_link: "",
    keywords: "",
  },
  {
    id: "330393",
    ident: "02XA",
    type: "small_airport",
    name: "JLS Farms Airport",
    latitude_deg: "33.591319",
    longitude_deg: "-95.882864",
    elevation_ft: "675",
    continent: "NA",
    iso_country: "US",
    iso_region: "US-TX",
    municipality: "Honey Grove",
    scheduled_service: "no",
    gps_code: "02XA",
    iata_code: "",
    local_code: "02XA",
    home_link: "",
    wikipedia_link: "",
    keywords: "",
  },
  {
    id: "6695",
    ident: "02XS",
    type: "closed",
    name: "Seidel Ranch Airport",
    latitude_deg: "30.100941",
    longitude_deg: "-97.672607",
    elevation_ft: "510",
    continent: "NA",
    iso_country: "US",
    iso_region: "US-TX",
    municipality: "Austin",
    scheduled_service: "no",
    gps_code: "",
    iata_code: "",
    local_code: "",
    home_link: "",
    wikipedia_link: "",
    keywords: "02XS, 02XS, 02XS",
  },
  {
    id: "325508",
    ident: "03AA",
    type: "heliport",
    name: "Trapper T Heliport",
    latitude_deg: "61.556055",
    longitude_deg: "-149.284527",
    elevation_ft: "159",
    continent: "NA",
    iso_country: "US",
    iso_region: "US-AK",
    municipality: "Palmer",
    scheduled_service: "no",
    gps_code: "03AA",
    iata_code: "",
    local_code: "03AA",
    home_link: "",
    wikipedia_link: "",
    keywords: "",
  },
  {
    id: "6696",
    ident: "03AK",
    type: "seaplane_base",
    name: "Joe Clouds Seaplane Base",
    latitude_deg: "60.72722244262695",
    longitude_deg: "-151.13278198242188",
    elevation_ft: "150",
    continent: "NA",
    iso_country: "US",
    iso_region: "US-AK",
    municipality: "Kenai",
    scheduled_service: "no",
    gps_code: "03AK",
    iata_code: "",
    local_code: "03AK",
    home_link: "",
    wikipedia_link: "",
    keywords: "",
  },
  {
    id: "6697",
    ident: "03AL",
    type: "heliport",
    name: "Highland Medical Center Heliport",
    latitude_deg: "34.662604",
    longitude_deg: "-86.046774",
    elevation_ft: "628",
    continent: "NA",
    iso_country: "US",
    iso_region: "US-AL",
    municipality: "Scottsboro",
    scheduled_service: "no",
    gps_code: "03AL",
    iata_code: "",
    local_code: "03AL",
    home_link: "",
    wikipedia_link: "",
    keywords: "Jackson County Hospital Heliport",
  },
  {
    id: "6698",
    ident: "03AR",
    type: "heliport",
    name: "Hscmh Heliport",
    latitude_deg: "34.357601165771484",
    longitude_deg: "-92.78849792480469",
    elevation_ft: "350",
    continent: "NA",
    iso_country: "US",
    iso_region: "US-AR",
    municipality: "Malvern",
    scheduled_service: "no",
    gps_code: "03AR",
    iata_code: "",
    local_code: "03AR",
    home_link: "",
    wikipedia_link: "",
    keywords: "",
  },
  {
    id: "6699",
    ident: "03AZ",
    type: "small_airport",
    name: "Thompson International Aviation Airport",
    latitude_deg: "31.430971",
    longitude_deg: "-110.088087",
    elevation_ft: "4275",
    continent: "NA",
    iso_country: "US",
    iso_region: "US-AZ",
    municipality: "Hereford",
    scheduled_service: "no",
    gps_code: "03AZ",
    iata_code: "",
    local_code: "03AZ",
    home_link: "",
    wikipedia_link: "",
    keywords: "",
  },
];
